plugins { id 'com.android.application' }

android {
    namespace 'com.matkakingfatafat.app'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.matkakingfatafat.app'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    flavorDimensions += 'app'
    productFlavors {
        publicApp {
            dimension 'app'
            applicationIdSuffix '.public'
            versionNameSuffix '-public'
            buildConfigField 'String', 'SITE_URL', '"https://matkakingfatafat-bice.vercel.app/"'
        }
        adminApp {
            dimension 'app'
            applicationIdSuffix '.admin'
            versionNameSuffix '-admin'
            buildConfigField 'String', 'SITE_URL', '"https://matkakingfatafat-bice.vercel.app/admin"'
        }
    }
}

dependencies {
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
